- name: Remove pgdata
  file:
    path: /var/lib/pgsql/11/data
    state: absent

- name: Create DB pgdata
  file:
    path: /var/lib/pgsql/11/data
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Sync DB
  command: pg_basebackup -X stream -h {{ master_ip }} -D /var/lib/pgsql/11/data/ -P -U replication
  become: yes
  become_user: postgres

- name: Create recovery.conf
  template:
    src: recovery.conf.j2
    dest: /var/lib/pgsql/11/data/recovery.conf
    owner: postgres
    group: postgres
    mode: '0600'

- name: Restart PostgreSQL
  systemd:
    name: postgresql-11
    state: restarted
